name: Check PHP code style using phpcs

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Check code style (config from phpcs.xml.dist)
        run: vendor/bin/phpcs -v

      - name: Check code quality
        run: vendor/bin/phpstan analyse -l 7 src/